export type ChasePassage = { title: string; text: string };

export const CHASE_PASSAGES: ChasePassage[] = [
  {
    title: "The Lighthouse Signal",
    text: `Maya had visited the old lighthouse many times, but she had never climbed its narrow stairs after sunset. One windy evening, the harbor keeper noticed that the lamp had stopped turning. A fishing boat was still beyond the rocks, and without the light its crew might miss the safe channel home. Maya grabbed a small tool bag and followed the keeper inside. The wooden steps groaned as they hurried upward. Halfway to the top, they heard a loose window banging against the stone wall. At last they reached the lamp room and found a broken drive belt beside the great glass lens. The keeper searched his cabinet, but the spare belt was gone. Maya looked through the tool bag and found a length of strong cord. She tied it around the wheels, pulled the knot tight, and asked the keeper to test the motor. Slowly, the lens began to turn. A bright beam swept across the dark water and flashed over the distant boat. Minutes later, two short horn calls answered from the bay. The fishing boat changed course and entered the safe channel. When Maya stepped outside, the wind was still cold, but the harbor below looked warm and peaceful. The keeper smiled and told her that quick thinking could shine as brightly as any lighthouse.`,
  },
  {
    title: "The Garden Behind the School",
    text: `At the back of River Street School stood a patch of ground that everyone ignored. It was filled with stones, dry weeds, and one rusty wheelbarrow. During science class, Mr. Chen asked his students what might happen if they treated the empty space like a living laboratory. The class decided to build a garden. On Monday they cleared the weeds and sorted the stones into a low border. On Tuesday they mixed fallen leaves into the soil. Each group chose something different to plant, including beans, tomatoes, sunflowers, mint, and strawberries. The first week brought no visible change, and several students wondered whether the seeds had failed. Then a thin green shoot appeared beside a label marked beans. More shoots followed after a night of gentle rain. The students measured them every morning and wrote the results in a shared notebook. They learned that the sunny corner dried faster, while the shaded bed stayed damp. They moved the mint, added mulch, and built a simple watering schedule. By early summer, yellow flowers leaned over the border and bees moved quietly between them. The first tomato was too small to divide among the whole class, so they placed it on the teacher's desk like a trophy. The forgotten ground had become the busiest and most carefully observed part of the school.`,
  },
  {
    title: "A Map in the Library",
    text: `Noah liked the town library because every shelf seemed to hold a doorway into another place. One rainy afternoon, he opened a thick book about local history and discovered a folded map between two pages. It showed the streets around the library, but several buildings had names he did not recognize. A bakery stood where the bus station was now, and a tiny theater appeared beside the river. In one corner, someone had drawn a blue circle around an oak tree and written, Meet here when the clock strikes four. Noah showed the map to the librarian, Mrs. Patel. She examined the paper and guessed that it came from a children's club that had met nearly seventy years earlier. Together they searched old newspapers stored on a computer. They found a photograph of six children beside a huge oak tree, each holding a library book. The article explained that the club had planted a metal box containing letters to future readers. The oak tree still grew in the park across the street. Noah and Mrs. Patel contacted the town museum before touching anything. The next week, a museum worker carefully opened the ground near the roots and found the box. Inside were six letters, a marble, a train ticket, and a list of favorite stories. The library displayed copies of the letters, and Noah started a new club so today's readers could write messages to the future.`,
  },
  {
    title: "The Midnight Garden",
    text: `Lena woke when rain tapped softly against her window. At first she thought the sound was part of a dream, but then she noticed a small green light moving across the garden. She pulled on a sweater and went downstairs. Her grandfather was already in the kitchen, holding a lantern and a basket. He explained that the town's night-blooming flowers opened only during a warm summer storm. The flowers were rare, and a strong wind could scatter their seeds before anyone collected them. Lena followed him along the wet path. Silver drops clung to every leaf, and tiny frogs called from the flower beds. Near the old stone wall, a group of pale flowers opened like folded stars. Grandfather placed a cloth beneath the stems while Lena counted each seed pod. A sudden gust shook the branches above them. Lena saw one pod roll toward a drain and caught it with the edge of her boot. They worked quickly, tying the pods to short sticks and covering the smallest plants with jars. By dawn, the rain had stopped. The garden looked ordinary again, but their basket held enough seeds for a new bed. In spring, Lena planted the first row beside the kitchen door. Whenever the flowers opened, she remembered that a quiet night could hide important work.`,
  },
  {
    title: "The Paper Bridge",
    text: `Every Friday, the students in Room Twelve built something from simple materials. This week their teacher placed paper, tape, and two wooden blocks on each table. The challenge was to make a bridge that could hold a stack of books. Priya folded her paper into long strips, but the first bridge bent as soon as she added one book. Marcus made a flat bridge that looked strong, yet it slipped between the blocks. Instead of starting over alone, the two classmates compared their ideas. Priya noticed that a folded strip was stiffer than a flat sheet. Marcus suggested making several small folds across the bridge, like the ridges on a fan. They tested a new design and added tape only where the paper joined. The bridge held three books, then four. When another group asked for help, Priya explained that strength did not always come from using more material. It could come from changing the shape. The class tested arches, triangles, and rolled tubes until the final minute. Their best bridge carried a heavy dictionary and a small plant. The teacher asked everyone to write down one failed idea and one useful discovery. Priya wrote that the first bridge had not been wasted. It had shown her exactly where the next design needed to change.`,
  },
  {
    title: "The Lost Kite",
    text: `Eli and his sister June took their brightest kite to the hill above the soccer field. The kite had a red tail, two yellow stars, and a small bell tied to its frame. A steady breeze lifted it higher and higher until the string suddenly went slack. The kite sailed over the trees and disappeared behind a row of houses. June wanted to run straight down the hill, but Eli remembered that the wind had been blowing toward the old orchard. They checked the path, crossed the footbridge, and listened for the bell. At the edge of the orchard, a gardener waved from beneath an apple tree. He had found the kite caught in a high branch, but the string was wrapped around a nest. Eli and June thanked him and waited while he brought a long pole from his shed. He freed the string without touching the nest. The kite was torn near one star, so the children carried it to the garden table. June used red paper for the missing patch, while Eli replaced the bell with a smaller one. They returned to the hill before sunset. The kite did not fly as high as before, but it climbed steadily and made a softer sound. June said the repair made it special. Eli agreed. The best adventures, he decided, often left a mark.`,
  },
  {
    title: "The Clockwork Bird",
    text: `In the corner of the town museum stood a small metal bird inside a glass case. A label said that it had once sung three different tunes, but no one had heard it for many years. On a quiet afternoon, museum helper Sam found a loose key beneath the case. He took it to Ms. Alvarez, the curator, instead of turning it himself. Together they opened a hidden panel and discovered a row of tiny gears covered with dust. The museum's old instruction book showed how each gear should fit, but one spring was missing. Sam searched the workshop and found a similar spring in a box of broken toys. It was not the exact size, so Ms. Alvarez trimmed it carefully and placed it beside the largest gear. Sam cleaned the teeth with a soft brush while she tightened the screws. When they turned the key, the bird moved its head but made no sound. They checked each gear again and found a thread caught between two wheels. After removing it, they tried once more. The bird lifted its wings and played a clear, cheerful tune. Visitors gathered around the case, surprised by the sudden music. Sam wrote a new note for the display: Old machines may need patience before they can tell their stories again. The museum kept the note beside the original label.`,
  },
  {
    title: "The Mountain Picnic",
    text: `The hiking club planned a picnic beside a mountain lake, but the weather changed before the group reached the trailhead. Gray clouds covered the peak, and a cold wind pushed leaves across the parking lot. The leader, Mrs. Green, asked everyone to check their water, jackets, and maps. A few hikers felt disappointed when she chose a shorter path, yet nobody argued. The new trail followed a line of pine trees and climbed gently toward a small lookout. Halfway up, the group heard a whistle from below. A younger hiker named Tom had stopped to tie his shoe and could no longer see the others. Mrs. Green called back and waited until he reached the trail. At the lookout, the clouds opened for a moment. The lake shone between the trees, and a rainbow curved over the far shore. Since the picnic area was too wet, the group spread their blankets beneath a rocky overhang. They shared sandwiches, apples, and a bag of warm muffins. Tom found a smooth blue stone near the wall and gave it to Mrs. Green as a thank you. On the way down, the rain began again, but everyone walked carefully and stayed together. The lake picnic had not happened as planned. Still, the club returned with a better story than an ordinary sunny afternoon could have given them.`,
  },
  {
    title: "The Secret Treehouse",
    text: `Behind the community center grew a tall oak tree with a narrow wooden ladder fixed to its trunk. The ladder led to a treehouse that had been locked for years. When Ava joined the neighborhood cleanup, she asked why nobody used it. The caretaker explained that the roof leaked and the floor needed new boards. Ava made a list of supplies and invited three friends to help. They swept away leaves, carried up safe boards, and painted the door bright blue. While removing an old shelf, they found a tin box filled with notes from children who had visited the treehouse long ago. One note described a hidden view of the river. Another asked future visitors to add their own discoveries. The friends repaired the shelf and placed the notes inside a clear folder. Then they climbed to the highest window and saw the river flashing beyond the rooftops. Ava wrote a new note about the view, but she also added a rule: Leave the treehouse ready for the next person. The caretaker gave them a small brass key and said they could open the door every Saturday. Soon the treehouse became a quiet reading place. Children brought comics, field guides, and notebooks. Nobody called it secret anymore, but the blue door still made it feel like a special place waiting to be found.`,
  },
  {
    title: "The Rainy Day Robot",
    text: `When heavy rain canceled the school fair, the students in the makers' club moved their project indoors. They had planned to show a small robot that carried cups from one table to another. The robot worked well on the gym floor, but it kept turning in circles on the classroom carpet. Its wheels slipped whenever it reached the thick rug near the window. Nia suggested adding rubber bands around the wheels. Omar wanted to change the motor speed. Instead of guessing, the students marked a test course with tape and measured each attempt. They learned that the robot veered left only when its front wheel crossed the rug. They cleaned the wheel, tightened a loose screw, and added a thin cardboard guide to the front. The robot crossed the rug twice, then stopped beside the cup table. Everyone cheered, but Nia noticed that the guide scraped the floor. The team shortened it and tested again. This time the robot rolled smoothly from the door to the table and back. The fair was still canceled, yet the club invited parents to watch the indoor demonstration. The robot delivered a cup of pencils to each visitor without spilling one. Their teacher said the rainy day had given them something sunny: time to observe a problem carefully. The students wrote their measurements in a notebook so they could improve the robot again next week.`,
  },
];

export function randomChasePassage(random = Math.random): ChasePassage {
  return CHASE_PASSAGES[Math.floor(random() * CHASE_PASSAGES.length)]!;
}
